import type { Vehicle, Category, Service } from "./types"

export const categories: Category[] = [
  { id: "cars", name: "Легковые авто", icon: "car", image: "/placeholder.svg?height=80&width=120" },
  { id: "new-cars", name: "Новые авто", icon: "sparkles", image: "/placeholder.svg?height=80&width=120" },
  { id: "select", name: "Селект", icon: "star", image: "/placeholder.svg?height=80&width=120" },
  { id: "trucks", name: "Грузовики и спецтехника", icon: "truck", image: "/placeholder.svg?height=80&width=120" },
  { id: "moto", name: "Мотоциклы и мототехника", icon: "bike", image: "/placeholder.svg?height=80&width=120" },
  { id: "rent-car", name: "Аренда авто", icon: "key", image: "/placeholder.svg?height=80&width=120" },
  { id: "rent-equipment", name: "Аренда техники", icon: "settings", image: "/placeholder.svg?height=80&width=120" },
  { id: "parts", name: "Запчасти", icon: "cog", image: "/placeholder.svg?height=80&width=120" },
]

export const services: Service[] = [
  { id: "catalog", name: "Каталог автомобилей", icon: "book" },
  { id: "journal", name: "Журнал", icon: "newspaper" },
  { id: "garage", name: "Гараж", icon: "warehouse" },
  { id: "history", name: "Проверка истории авто", icon: "shield-check" },
  { id: "contract", name: "Договор купли-продажи", icon: "file-text" },
  { id: "rating", name: "Авито Оценка", icon: "badge-check" },
  { id: "auction", name: "Продажа на аукционе", icon: "gavel" },
  { id: "credit", name: "Кредиты", icon: "calculator" },
  { id: "osago", name: "Оформление ОСАГО", icon: "shield" },
]

export const vehicles: Vehicle[] = [
  {
    id: "1",
    title: "Mazda 323 1.5 MT",
    price: 90000,
    year: 1999,
    mileage: 330000,
    engine: "Бензин 1.5 (88 л.с.)",
    transmission: "механика",
    drive: "передний",
    bodyType: "седан",
    location: "Московская обл., г.о. Ступино, ТСН Антей",
    timeAgo: "1 час назад",
    images: ["/placeholder.svg?height=300&width=400"],
    priceType: "sale",
  },
  {
    id: "2",
    title: "Chery T21FL",
    price: 300,
    priceType: "rent",
    year: 2016,
    mileage: 0,
    engine: "",
    transmission: "",
    drive: "",
    bodyType: "",
    location: "Новосибирская обл., Новосибирск",
    timeAgo: "2 часа назад",
    images: ["/placeholder.svg?height=300&width=400"],
  },
  {
    id: "3",
    title: "Geely Emgrand EC7 1.5 MT",
    price: 349000,
    pricePerMonth: 7510,
    year: 2013,
    mileage: 136521,
    engine: "Бензин 1.5 (98 л.с.)",
    transmission: "механика",
    drive: "передний",
    bodyType: "седан",
    location: "Нижегородская обл., Нижний Новгород",
    timeAgo: "1 час назад",
    images: ["/placeholder.svg?height=300&width=400"],
    hasCredit: true,
    priceType: "sale",
  },
  {
    id: "4",
    title: "Лодка Навигатор 270",
    price: 20000,
    year: 2020,
    mileage: 0,
    engine: "",
    transmission: "",
    drive: "",
    bodyType: "лодка",
    location: "Ростовская обл., Неклиновский р-н",
    timeAgo: "2 часа назад",
    images: ["/placeholder.svg?height=300&width=400"],
    priceType: "sale",
  },
  {
    id: "5",
    title: "Kia Rio 1.6 AT",
    price: 899999,
    originalPrice: 980000,
    year: 2016,
    mileage: 85000,
    engine: "Бензин 1.6 (123 л.с.)",
    transmission: "автомат",
    drive: "передний",
    bodyType: "седан",
    location: "Нижегородская обл., Нижний Новгород",
    timeAgo: "3 дня назад",
    images: ["/placeholder.svg?height=300&width=400"],
    badges: ["Надёжный партнёр"],
    priceType: "sale",
  },
  {
    id: "6",
    title: "Kia Rio 1.6 AT",
    price: 799000,
    year: 2016,
    mileage: 92000,
    engine: "Бензин 1.6 (123 л.с.)",
    transmission: "автомат",
    drive: "передний",
    bodyType: "седан",
    location: "Москва",
    timeAgo: "7 дней назад",
    images: ["/placeholder.svg?height=300&width=400"],
    badges: ["1 владелец"],
    priceType: "sale",
  },
]

export const subcategories = [
  "Автомобили",
  "Запчасти и аксессуары",
  "Мотоциклы и мототехника",
  "Грузовики и спецтехника",
]

export const vehicleSubcategories = [
  "Грузовики",
  "Тягачи",
  "Прицепы",
  "Шины",
  "Сельхозтехника",
  "Ещё",
]

export const journalArticles = [
  {
    id: "1",
    title: "Как выбрать авто из рейтингов и топорок",
    image: "/placeholder.svg?height=150&width=200",
  },
  {
    id: "2",
    title: "Зовите всех на Форум Авто",
    image: "/placeholder.svg?height=150&width=200",
  },
  {
    id: "3",
    title: "Автоответы в чатах",
    image: "/placeholder.svg?height=150&width=200",
  },
]
